### PR TITLE
Don't validate JSON records against the table schema

### PR DESCRIPTION
**Pull request by genzgd**
JSON records don't normally have to match the table schema.  Unknown fields can be ignored (with a setting), and missing fields will use defaults.

### CODE REVIEW

**Comment by genzgd** [comment]
I don't understand why this think it has a conflict?

**Review by mshustov — APPROVED** [review]
@genzgd could you create an issue to add tests later?

**Comment by genzgd** [comment]
I think we generally need integration [tests](https://github.com/ClickHouse/clickhouse-kafka-connect/issues/4) for this section.  Unit tests won't mean much.

**Comment by mshustov** [comment]
@genzgd agreed

**Pull request merged**
