### PR TITLE
Adding bytes support

### PR DESCRIPTION
**Pull request by Paultagoras**
## Checklist
Delete items not relevant to your PR:
- [ ] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

**Review by mzitnik — APPROVED** [review]
LGTM

**Comment by zcistkidd** [comment]
Hi @Paultagoras, Thx for the quick response,and for simple bytes, it is working as expected. 
But When I tried many complex tables, I encountered with following errors:
[2023-10-19 22:07:41,688] WARN [clickhouse-sink|task-0] Deciding how to handle exception: Failed making field 'java.nio.ByteBuffer#hb' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type. (com.clickhouse.kafka.connect.util.Utils:51)
[2023-10-19 22:07:41,688] ERROR [clickhouse-sink|task-0] WorkerSinkTask{id=clickhouse-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: com.google.gson.JsonIOException: Failed making field 'java.nio.ByteBuffer#hb' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type. (org.apache.kafka.connect.runtime.WorkerSinkTask:616)
java.lang.RuntimeException: com.google.gson.JsonIOException: Failed making field 'java.nio.ByteBuffer#hb' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:95)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:186)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:46)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:101)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:91)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.google.gson.JsonIOException: Failed making field 'java.nio.ByteBuffer#hb' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:38)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:286)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.Gson.getAdapter(Gson.java:556)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:55)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
        at com.google.gson.Gson.toJson(Gson.java:842)
        at com.google.gson.Gson.toJson(Gson.java:812)
        at com.google.gson.Gson.toJson(Gson.java:759)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertJson(ClickHouseWriter.java:588)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:175)
        ... 16 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field final byte[] java.nio.ByteBuffer.hb accessible: module java.base does not "opens java.nio" to unnamed module @683e44ed
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:35)
        ... 27 more
[2023-10-19 22:07:41,691] ERROR [clickhouse-sink|task-0] WorkerSinkTask{id=clickhouse-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:212)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:618)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:336)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:204)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:259)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:181)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: com.google.gson.JsonIOException: Failed making field 'java.nio.ByteBuffer#hb' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
        at com.clickhouse.kafka.connect.util.Utils.handleException(Utils.java:95)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:186)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doInsert(Processing.java:46)
        at com.clickhouse.kafka.connect.sink.processing.Processing.doLogic(Processing.java:101)
        at com.clickhouse.kafka.connect.sink.ProxySinkTask.put(ProxySinkTask.java:91)
        at com.clickhouse.kafka.connect.sink.ClickHouseSinkTask.put(ClickHouseSinkTask.java:60)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        ... 11 more
Caused by: com.google.gson.JsonIOException: Failed making field 'java.nio.ByteBuffer#hb' accessible; either increase its visibility or write a custom TypeAdapter for its declaring type.
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:38)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:286)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.Gson.getAdapter(Gson.java:556)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:55)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
        at com.google.gson.Gson.toJson(Gson.java:842)
        at com.google.gson.Gson.toJson(Gson.java:812)
        at com.google.gson.Gson.toJson(Gson.java:759)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsertJson(ClickHouseWriter.java:588)
        at com.clickhouse.kafka.connect.sink.db.ClickHouseWriter.doInsert(ClickHouseWriter.java:175)
        ... 16 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field final byte[] java.nio.ByteBuffer.hb accessible: module java.base does not "opens java.nio" to unnamed module @683e44ed
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:35)
        ... 27 more

**Comment by zcistkidd** [comment]
The version I am using is a local build from this commit

**Comment by zcistkidd** [comment]
`aa.a` Array(Int32) DEFAULT [],
    `aa.b` Array(Int64) DEFAULT [],
    `aa.c` Array(Int32) DEFAULT [],
    `aa.d` Array(UInt64) DEFAULT [],
    `aa.e` Array(UInt64) DEFAULT [],
    `aa_bb.a` Array(Int32) DEFAULT [],
    `aa_bb.b` Array(Int32) DEFAULT [],
    `aa_bb.c` Array(String) DEFAULT [],
    `aa_bb.d` Array(Int64) DEFAULT [],
    `aa_bb.e` Array(UInt8) DEFAULT [],
    `aa_bb.f` Array(UInt64) DEFAULT [],
    `aa_bb.g` Array(UInt64) DEFAULT [],

**Comment by zcistkidd** [comment]
This is the column setting for destination table

**Pull request merged**
