### PR TITLE
Update KeeperStateProvider.java

### PR DESCRIPTION
**Pull request by Paultagoras**
This should resolve https://github.com/ClickHouse/clickhouse-kafka-connect/issues/375

### CODE REVIEW

**Comment by abhishekgahlot2** [comment]
Nice!

**Comment by abhishekgahlot2** [comment]
@Paultagoras I don't see much difference except just some very minor lag of updated values between table in cluster. Not sure if thats going to affect any events

**Review by mzitnik — CHANGES_REQUESTED** [review]
Can we add a test for it?

**Review by mzitnik — APPROVED** [review]
Ok, but please documentation in our main docs repo

**Comment by mzitnik** [comment]
@Paultagoras i see one of our cloud tests is falling please take a look before

**Pull request merged**
